import React, { useState } from 'react';
import { X, Building2, Truck, Users, Landmark, Plus, CheckCircle, TrendingUp, AlertCircle } from 'lucide-react';
import { Garage, HiredDriver, PlayerCareer, TruckConfig } from '../../types/game';
import { AVAILABLE_TRUCK_MODELS, EUROPEAN_CITIES, INITIAL_DRIVERS_POOL } from '../../data/gameData';
import { truckAudio } from '../../services/sound';

interface CompanyFleetModalProps {
  career: PlayerCareer;
  onBuyTruck: (truck: TruckConfig) => void;
  onHireDriver: (driver: HiredDriver) => void;
  onAssignDriverTruck: (driverId: string, truckId: string) => void;
  onBuyGarage: (cityId: string, cost: number) => void;
  onTakeLoan: (amount: number) => void;
  onRepayLoan: (amount: number) => void;
  onCollectDriverIncome: () => void;
  onClose: () => void;
}

export const CompanyFleetModal: React.FC<CompanyFleetModalProps> = ({
  career,
  onBuyTruck,
  onHireDriver,
  onAssignDriverTruck,
  onBuyGarage,
  onTakeLoan,
  onRepayLoan,
  onCollectDriverIncome,
  onClose,
}) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'dealership' | 'drivers' | 'garages' | 'bank'>('overview');

  // Compute total passive earnings generated by working drivers
  const workingDrivers = career.drivers.filter((d) => d.assignedTruckId !== null);
  const totalDailyPassive = workingDrivers.reduce((sum, d) => sum + (d.dailyEarnings - d.salaryPerDay), 0);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-neutral-950/85 backdrop-blur-md">
      <div className="bg-neutral-900 border border-neutral-800 rounded-3xl w-full max-w-5xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden text-neutral-100">
        {/* Header */}
        <div className="px-6 py-5 border-b border-neutral-800 flex items-center justify-between bg-neutral-900/80">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center">
              <Building2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white flex items-center gap-2">
                <span>شركة {career.companyName} اللوجستية</span>
                <span className="text-xs bg-amber-500/20 text-amber-300 border border-amber-500/30 px-2 py-0.5 rounded-md font-normal">
                  المستوى {career.level}
                </span>
              </h2>
              <p className="text-xs text-neutral-400">
                إدارة أسطول الشاحنات، توظيف السائقين، توسعة شبكة المستودعات والكراجات في أوروبا
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-10 h-10 rounded-xl bg-neutral-800 hover:bg-neutral-700 flex items-center justify-center text-neutral-400 hover:text-white transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Financial Highlights Bar */}
        <div className="px-6 py-3.5 bg-neutral-950/60 border-b border-neutral-800 flex flex-wrap items-center justify-between gap-4 text-xs">
          <div className="flex items-center gap-6">
            <div>
              <span className="text-neutral-400">الرصيد المتاح:</span>
              <span className="mr-2 font-mono font-bold text-base text-amber-400">
                €{career.money.toLocaleString()}
              </span>
            </div>
            <div>
              <span className="text-neutral-400">الدخل اليومي التلقائي:</span>
              <span className="mr-2 font-mono font-bold text-emerald-400">
                +€{totalDailyPassive.toLocaleString()}/يوم
              </span>
            </div>
            {career.bankDebt > 0 && (
              <div>
                <span className="text-neutral-400">الديون المصرفية:</span>
                <span className="mr-2 font-mono font-bold text-rose-400">
                  €{career.bankDebt.toLocaleString()}
                </span>
              </div>
            )}
          </div>

          {workingDrivers.length > 0 && (
            <button
              onClick={() => {
                truckAudio.playCashPayout();
                onCollectDriverIncome();
              }}
              className="px-3.5 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg font-bold text-xs flex items-center gap-1.5 transition-colors cursor-pointer shadow-md"
            >
              <TrendingUp className="w-3.5 h-3.5" />
              <span>تحصيل أرباح السائقين الآن</span>
            </button>
          )}
        </div>

        {/* Tab Navigation */}
        <div className="px-6 py-2.5 border-b border-neutral-800 flex items-center gap-2 text-xs overflow-x-auto bg-neutral-900/40">
          {[
            { id: 'overview', label: 'نظرة عامة على الأسطول', icon: Building2 },
            { id: 'dealership', label: 'وكالة شراء الشاحنات', icon: Truck },
            { id: 'drivers', label: 'مكتب توظيف السائقين', icon: Users },
            { id: 'garages', label: 'شبكة الكراجات الأوروبية', icon: Building2 },
            { id: 'bank', label: 'القروض البنكية والتمويل', icon: Landmark },
          ].map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as typeof activeTab)}
                className={`flex items-center gap-2 px-3.5 py-1.5 rounded-xl whitespace-nowrap transition-colors cursor-pointer font-medium ${
                  activeTab === tab.id
                    ? 'bg-amber-500 text-neutral-950 font-bold'
                    : 'bg-neutral-800 text-neutral-300 hover:text-white'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Tab Content */}
        <div className="p-6 overflow-y-auto flex-1">
          {/* Overview Tab */}
          {activeTab === 'overview' && (
            <div className="space-y-6">
              {/* Quick KPI stats */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="p-4 rounded-2xl bg-neutral-950/60 border border-neutral-800">
                  <div className="text-xs text-neutral-400">إجمالي الشاحنات المملوكة</div>
                  <div className="text-2xl font-black font-mono text-white mt-1">
                    {career.ownedTrucks.length}
                  </div>
                </div>
                <div className="p-4 rounded-2xl bg-neutral-950/60 border border-neutral-800">
                  <div className="text-xs text-neutral-400">عدد السائقين الموظفين</div>
                  <div className="text-2xl font-black font-mono text-white mt-1">
                    {career.drivers.length}
                  </div>
                </div>
                <div className="p-4 rounded-2xl bg-neutral-950/60 border border-neutral-800">
                  <div className="text-xs text-neutral-400">الكراجات والمستودعات</div>
                  <div className="text-2xl font-black font-mono text-white mt-1">
                    {career.garages.length}
                  </div>
                </div>
                <div className="p-4 rounded-2xl bg-neutral-950/60 border border-neutral-800">
                  <div className="text-xs text-neutral-400">المسافة الإجمالية المقطوعة</div>
                  <div className="text-2xl font-black font-mono text-amber-400 mt-1">
                    {Math.round(career.totalDistanceDrivenKm)} كم
                  </div>
                </div>
              </div>

              {/* Owned Trucks List */}
              <div>
                <h3 className="text-sm font-bold text-neutral-200 mb-3 flex items-center gap-2">
                  <Truck className="w-4 h-4 text-amber-500" />
                  <span>شاحنات الأسطول الحالية:</span>
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {career.ownedTrucks.map((truck, idx) => {
                    const assignedDriver = career.drivers.find((d) => d.assignedTruckId === truck.id);
                    const isPlayerTruck = idx === career.currentTruckIndex;
                    return (
                      <div
                        key={truck.id}
                        className={`p-4 rounded-2xl border transition-all ${
                          isPlayerTruck ? 'border-amber-500 bg-neutral-950/70' : 'border-neutral-800 bg-neutral-950/40'
                        }`}
                      >
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex items-center gap-3">
                            <div
                              className="w-10 h-10 rounded-xl border border-white/20 flex items-center justify-center font-bold text-white text-xs font-mono"
                              style={{ backgroundColor: truck.color }}
                            >
                              V8
                            </div>
                            <div>
                              <div className="font-bold text-white text-sm">{truck.modelName}</div>
                              <div className="text-xs text-neutral-400">{truck.brand}</div>
                            </div>
                          </div>
                          {isPlayerTruck && (
                            <span className="text-[11px] bg-amber-500 text-neutral-950 font-bold px-2 py-0.5 rounded">
                              شاحنتك الحالية
                            </span>
                          )}
                        </div>

                        <div className="mt-3 text-xs text-neutral-400 flex items-center justify-between border-t border-neutral-800/80 pt-2.5">
                          <span>المحرك: <strong className="text-neutral-200">{truck.engineHp} HP</strong></span>
                          <span>الهيكل: <strong className="text-neutral-200">{truck.chassis}</strong></span>
                          <span>السائق: <strong className="text-amber-400">{isPlayerTruck ? 'أنت (المالك)' : assignedDriver ? assignedDriver.name : 'شاغرة'}</strong></span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}

          {/* Dealership Tab */}
          {activeTab === 'dealership' && (
            <div className="space-y-4">
              <h3 className="text-sm font-bold text-neutral-300">
                اختر شاحنة أوروبية جديدة لضمها إلى أسطول شركتك:
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {AVAILABLE_TRUCK_MODELS.map((model) => {
                  const canAfford = career.money >= model.price;
                  return (
                    <div
                      key={model.id}
                      className="p-5 rounded-2xl bg-neutral-950/70 border border-neutral-800 flex flex-col justify-between hover:border-amber-500/40 transition-all"
                    >
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <div>
                            <span className="text-xs text-amber-400 font-semibold">{model.brand}</span>
                            <h4 className="text-base font-bold text-white">{model.modelName}</h4>
                          </div>
                          <div
                            className="w-8 h-8 rounded-xl border border-white/20"
                            style={{ backgroundColor: model.color }}
                          />
                        </div>

                        <div className="my-3 p-3 bg-neutral-900 rounded-xl text-xs space-y-1.5 text-neutral-300">
                          <div className="flex justify-between">
                            <span className="text-neutral-400">قوة المحرك:</span>
                            <span className="font-bold text-amber-400">{model.engineHp} حصان</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-neutral-400">تكوين المحاور:</span>
                            <span className="font-bold text-neutral-200">{model.chassis}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-neutral-400">ناقل الحركة:</span>
                            <span className="font-bold text-neutral-200">{model.transmissionGears} سرعة</span>
                          </div>
                        </div>
                      </div>

                      <div className="pt-3 border-t border-neutral-800 flex items-center justify-between">
                        <div>
                          <div className="text-xs text-neutral-400">سعر الشراء:</div>
                          <div className="text-lg font-black font-mono text-white">
                            €{model.price.toLocaleString()}
                          </div>
                        </div>
                        <button
                          onClick={() => {
                            if (!canAfford) return;
                            truckAudio.playCashPayout();
                            onBuyTruck({ ...model, id: `truck_${Date.now()}` });
                          }}
                          disabled={!canAfford}
                          className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer ${
                            canAfford
                              ? 'bg-amber-500 hover:bg-amber-400 text-neutral-950 shadow-lg shadow-amber-500/20'
                              : 'bg-neutral-800 text-neutral-500 cursor-not-allowed'
                          }`}
                        >
                          {canAfford ? 'شراء وإضافة للأسطول' : 'رصيد غير كافٍ'}
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Drivers Tab */}
          {activeTab === 'drivers' && (
            <div className="space-y-4">
              <h3 className="text-sm font-bold text-neutral-300">
                توظيف سائقين محترفين وتعيينهم على الشاحنات الشاغرة لتحقيق أرباح مستمرة:
              </h3>

              {/* Pool of available drivers */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {INITIAL_DRIVERS_POOL.map((driver) => {
                  const isHired = career.drivers.some((d) => d.id === driver.id);
                  const hiredInstance = career.drivers.find((d) => d.id === driver.id);
                  const idleTrucks = career.ownedTrucks.filter(
                    (t, i) => i !== career.currentTruckIndex && !career.drivers.some((d) => d.assignedTruckId === t.id)
                  );

                  return (
                    <div
                      key={driver.id}
                      className="p-4 rounded-2xl bg-neutral-950/70 border border-neutral-800 flex flex-col justify-between"
                    >
                      <div>
                        <div className="flex items-center gap-3 mb-3">
                          <span className="text-3xl">{driver.avatar}</span>
                          <div>
                            <div className="font-bold text-white text-sm">{driver.name}</div>
                            <div className="text-xs text-amber-400">تقييم الكفاءة: {driver.rating} ★</div>
                          </div>
                        </div>

                        <div className="p-3 bg-neutral-900 rounded-xl text-xs space-y-1 text-neutral-400 mb-3">
                          <div className="flex justify-between">
                            <span>الراتب اليومي:</span>
                            <span className="font-bold text-rose-400">€{driver.salaryPerDay}/يوم</span>
                          </div>
                          <div className="flex justify-between">
                            <span>العائد اليومي المتوقع:</span>
                            <span className="font-bold text-emerald-400">+€{driver.dailyEarnings}/يوم</span>
                          </div>
                          <div className="flex justify-between">
                            <span>مسار النقل المخصص:</span>
                            <span className="text-neutral-200">{driver.assignedRoute}</span>
                          </div>
                        </div>
                      </div>

                      <div className="pt-3 border-t border-neutral-800 flex items-center justify-between">
                        {!isHired ? (
                          <button
                            onClick={() => {
                              truckAudio.playCashPayout();
                              onHireDriver(driver);
                            }}
                            className="w-full py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-bold transition-colors cursor-pointer"
                          >
                            توظيف في الشركة
                          </button>
                        ) : (
                          <div className="w-full flex items-center justify-between gap-2">
                            <span className="text-xs text-neutral-400">الشاحنة:</span>
                            {hiredInstance?.assignedTruckId ? (
                              <span className="text-xs text-emerald-400 font-bold flex items-center gap-1">
                                <CheckCircle className="w-3.5 h-3.5" />
                                <span>يقود شاحنة بالخدمة</span>
                              </span>
                            ) : idleTrucks.length > 0 ? (
                              <select
                                onChange={(e) => onAssignDriverTruck(driver.id, e.target.value)}
                                className="bg-neutral-800 text-white text-xs rounded px-2 py-1 outline-none border border-neutral-700"
                              >
                                <option value="">تعيين شاحنة شاغرة...</option>
                                {idleTrucks.map((t) => (
                                  <option key={t.id} value={t.id}>
                                    {t.modelName}
                                  </option>
                                ))}
                              </select>
                            ) : (
                              <span className="text-[11px] text-amber-400">
                                يلزم شراء شاحنة إضافية للتعيين
                              </span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Garages Tab */}
          {activeTab === 'garages' && (
            <div className="space-y-4">
              <h3 className="text-sm font-bold text-neutral-300">
                شراء كراجات جديدة في المدن الأوروبية لزيادة سعة استيعاب الشاحنات:
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {EUROPEAN_CITIES.map((city) => {
                  const owned = career.garages.some((g) => g.cityId === city.id);
                  const garageCost = 140000;
                  const canAfford = career.money >= garageCost;

                  return (
                    <div
                      key={city.id}
                      className={`p-4 rounded-2xl border transition-all ${
                        owned ? 'border-emerald-500/60 bg-neutral-950/80' : 'border-neutral-800 bg-neutral-950/40'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-bold text-base text-white">{city.name}</span>
                        <span className="text-xs text-neutral-400">{city.country}</span>
                      </div>
                      <p className="text-xs text-neutral-400 mb-4">{city.description}</p>

                      <div className="pt-3 border-t border-neutral-800 flex items-center justify-between text-xs">
                        {owned ? (
                          <span className="text-emerald-400 font-bold flex items-center gap-1">
                            <CheckCircle className="w-3.5 h-3.5" />
                            <span>كراج مملوك (سعة 3 شاحنات)</span>
                          </span>
                        ) : (
                          <>
                            <span className="font-mono text-amber-400 font-bold">€{garageCost.toLocaleString()}</span>
                            <button
                              onClick={() => {
                                if (!canAfford) return;
                                truckAudio.playCashPayout();
                                onBuyGarage(city.id, garageCost);
                              }}
                              disabled={!canAfford}
                              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-colors cursor-pointer ${
                                canAfford
                                  ? 'bg-amber-500 hover:bg-amber-400 text-neutral-950'
                                  : 'bg-neutral-800 text-neutral-500 cursor-not-allowed'
                              }`}
                            >
                              شراء الكراج
                            </button>
                          </>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Bank Loans Tab */}
          {activeTab === 'bank' && (
            <div className="space-y-4">
              <h3 className="text-sm font-bold text-neutral-300">
                القروض البنكية لتوسيع أسطولك بسرعة (تسديد مع فائدة مخفضة 5%):
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {[
                  { amount: 50000, label: 'قرض تمويل سريع' },
                  { amount: 120000, label: 'قرض شراء شاحنة ثقيلة' },
                  { amount: 350000, label: 'قرض تأسيس أسطول وكراج' },
                ].map((loan) => (
                  <div
                    key={loan.amount}
                    className="p-5 rounded-2xl bg-neutral-950/70 border border-neutral-800 flex flex-col justify-between"
                  >
                    <div>
                      <div className="text-sm font-bold text-white mb-1">{loan.label}</div>
                      <div className="text-2xl font-black font-mono text-amber-400 mb-3">
                        €{loan.amount.toLocaleString()}
                      </div>
                      <p className="text-xs text-neutral-400 mb-4">
                        تمويل مباشر يُضاف لرصيد حساب الشركة فوراً لتسهيل شراء شاحنات V8 وتوظيف سائقين.
                      </p>
                    </div>

                    <button
                      onClick={() => {
                        truckAudio.playCashPayout();
                        onTakeLoan(loan.amount);
                      }}
                      className="w-full py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold transition-colors cursor-pointer"
                    >
                      اقتراض المبلغ الآن
                    </button>
                  </div>
                ))}
              </div>

              {career.bankDebt > 0 && (
                <div className="mt-6 p-4 rounded-2xl bg-rose-950/30 border border-rose-900/50 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <AlertCircle className="w-5 h-5 text-rose-400 shrink-0" />
                    <div>
                      <div className="text-sm font-bold text-white">الديون المصرفية المستحقة حالياً:</div>
                      <div className="text-xs text-neutral-400">
                        مجموع المستحق: <strong className="text-rose-400 font-mono">€{career.bankDebt.toLocaleString()}</strong>
                      </div>
                    </div>
                  </div>
                  <button
                    onClick={() => onRepayLoan(Math.min(career.money, career.bankDebt))}
                    disabled={career.money < 1000}
                    className="px-4 py-2 bg-rose-600 hover:bg-rose-500 text-white rounded-xl text-xs font-bold transition-colors cursor-pointer"
                  >
                    سداد الديون من الرصيد
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
